### ISSUE TITLE
Deleting folders

### ISSUE THREAD

**Issue by AmimiHamza** [insea-connect/insea-connect-app#74]
when trying to delete a folder on the drive section , all folders got deleted

try creating many folders
then try to delete one of them

insead of deleteing the selected folder , all folders disappear

**Comment by Earthyyy** [comment]
@AmimiHamza Oh I will look into the issue. Thanks for reporting it!

**Comment by Earthyyy** [comment]
@AmimiHamza Can you provide more details, because I couldn't recreate the issue. Here's what I did:

**The endpoint:**  DELETE /api/v1/drive/items/{itemId}

## The initial view

![image](https://github.com/insea-connect/insea-connect-app/assets/93055532/fd063fd7-f03c-40c1-b9f6-75af4c7c01b6)

### _Sample 0_ items
![image](https://github.com/insea-connect/insea-connect-app/assets/93055532/ac8796b5-2aea-4508-8413-08254ca73ddb)

### _Sample 0.1_ items
![image](https://github.com/insea-connect/insea-connect-app/assets/93055532/fcbf9785-8d01-460f-b6dd-dfa5e8fe092a)

## After Deleting Sample 0

![image](https://github.com/insea-connect/insea-connect-app/assets/93055532/7a008b0e-3ba4-4a9c-af5e-7a274bef1f27)

None of the other folders are impacted. Only Sample 0 and his descendant children

### Trying to access _Sample 0.1_ But found nothing (Previously contained _Sample 0.1.1_)

![image](https://github.com/insea-connect/insea-connect-app/assets/93055532/b356a9ee-5a02-49d7-bc96-ce3262dc80fd)
